spring.datasource.url=jdbc:postgresql://localhost:5432/personal_data_inventory
spring.datasource.username=postgres
spring.datasource.password=2580

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080