# ===============================
# 🔹 DATABASE CONFIG (PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/personal_data_inventory
spring.datasource.username=postgres
spring.datasource.password=2580

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# 🔹 SERVER CONFIG
# ===============================
server.port=8080


# ===============================
# 🔹 REDIS CACHE
# ===============================
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379


# ===============================
# 🔹 JWT CONFIG
# ===============================
jwt.secret=your_secret_key_here
jwt.expiration=86400000


# ===============================
# 🔹 EMAIL CONFIG (FIXED)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yashashjhj@gmail.com
spring.mail.password=dnwwjxrsyrowamgk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# ===============================
# 🔹 SWAGGER CONFIG
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


# ===============================
# 🔹 ACTUATOR CONFIG
# ===============================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always


# ===============================
# 🔹 LOGGING (DAY 10 IMPORTANT)
# ===============================
logging.level.root=INFO
logging.level.com.internship.tool=DEBUG